package.json

Resolves this problem
```Running webpack ...
WARNING: Invalid value for $grid-breakpoints: This map must be in ascending order, but key 'xxs' has value 0 which isn't greater than 1200px, the value of the previous key 'xl' !
on line 16 of node_modules/bootstrap/scss/_functions.scss, in mixin `-assert-ascending`
from line 201 of node_modules/bootstrap/scss/_variables.scss
from line 9 of src/AppBundle/Resources/sass/bootstrap_import/_bootstrap.scss
from line 3 of src/AppBundle/Resources/sass/bootstrap_import/_bootstrap_import.scss
from line 9 of stdin
WARNING: First breakpoint in `$grid-breakpoints` must start at 0, but starts at 480px.
on line 29 of node_modules/bootstrap/scss/_functions.scss, in mixin `-assert-starts-at-zero`
from line 202 of node_modules/bootstrap/scss/_variables.scss …
```

bootstrap package in v4.2 should not be used

---

src/AppBundle/Resources/views/themes/app/info_collection/email.html.twig

`subject` block is rendered standalone, separately from the rest of the template so it not aware of `site_name` declaration and one should be moved inside `subject` block.

Declaration of site_name variable should be moved inside subject block

---

src/AppBundle/Resources/views/themes/common/parts/related_multimedia/ng_video.html.twig
src/AppBundle/Resources/views/themes/common/parts/video.html.twig

Autoplay variable inside player macro had is_slider as condiditon but is_slider was not passed as argument.
Also true is now passed from ng_video so it can have same behaviour as earlier.

Add is_slider argument to player macro

---

src/AppBundle/AppBundle.php
src/AppBundle/DependencyInjection/CompilerPass/DisableLegacyContentViewFallbackPass.php

This disables Legacy Stack Content View fallback for eZ Platform and Site API Content Views.
Because view providers are registered through compiler pass in the `EzPublishCoreBundle`, this first redefines the services without the `ezpublish.view_provider` tag, so they can be removed without the depending services crashing.

NGSTACK-376: disable Legacy Stack Content View fallback

---

src/AppBundle/DependencyInjection/AppExtension.php
src/AppBundle/Resources/config/content_view.yml
src/AppBundle/Resources/config/ezplatform.yml

Since we already use a separate file for the content view configuration, we can use extension config prepend to reduce unnecessary indentation and make it a little bit easier to read and edit.

Reduce content view config indentation

---

composer.json
src/AppBundle/Resources/config/content_view.yml

Update view configuration in media-site to use template pattern matching and view config inheritance

NGSTACK-394 update view configuration to use pattern matching and inheritance

---

src/AppBundle/Resources/views/themes/app/content/full/ng_feedback_form.html.twig
src/AppBundle/Resources/views/themes/app/forms/theme.html.twig
src/AppBundle/Resources/views/themes/app/user/activate.html.twig
src/AppBundle/Resources/views/themes/app/user/forgot_password.html.twig
src/AppBundle/Resources/views/themes/app/user/reset_password.html.twig

- change the base Symfony form theme we are extending in the custom form theme from "form_div_layout" to "bootstrap_4_layout". We are using bootstrap 4 in the current website frontend.
- this also solves the visual/markup problem with rendering certain Symfony form fields on the frontend (checkboxes, radio buttons, date and date/time)
- remove form-control CSS class from all form_row elements, it is now added through the theme
- apply custom form theme in all templates where we render Symfony forms.

NGSTACK-458

---

src/AppBundle/Resources/views/themes/app/content/listitem/ng_article.html.twig
src/AppBundle/Resources/views/themes/app/content/listitem/ng_audio.html.twig
src/AppBundle/Resources/views/themes/app/content/listitem/ng_blog_post.html.twig
src/AppBundle/Resources/views/themes/app/content/listitem/ng_gallery.html.twig
src/AppBundle/Resources/views/themes/app/content/listitem/ng_news.html.twig
src/AppBundle/Resources/views/themes/app/content/listitem/ng_recipe.html.twig
src/AppBundle/Resources/views/themes/app/content/listitem/ng_video.html.twig

Until now, only fallback listitem template had a logic with with_intro parameter to display the intro. 
All specific templates did not have this, so this PR enables this to make it work.

NGSTACK-476 - Add logic for with_intro on listitem_with_intro templates

---

src/AppBundle/Resources/config/content_view.yml
src/AppBundle/Resources/sass/content/item_view_types/_line.scss
src/AppBundle/Resources/sass/content/item_view_types/_overlay.scss
src/AppBundle/Resources/views/themes/app/content/line/ng_banner.html.twig
src/AppBundle/Resources/views/themes/app/content/listitem/ng_banner.html.twig
src/AppBundle/Resources/views/themes/app/content/mini/ng_banner.html.twig
src/AppBundle/Resources/views/themes/app/content/overlay/ng_banner.html.twig
src/AppBundle/Resources/views/themes/common/parts/macros.html.twig

Overlay template for ng_banner was much more specific than the rest of the templates for banners, mostly because of different style it has to have (image with overlay, absolutely positioned elements, etc...)
Also, it required a special content_link_parameters macro which was used only on this template, and used as a parameter for link, which looked a bit dirty. 
With this change, overlay ng_banner uses the same macros as other BIVT ng_banner templates, without a need for special requirements.

NGSTACK-452 - consolidate overlay ng_banner markup and styling

---

src/AppBundle/Resources/es6/ngsite.js
src/AppBundle/Resources/views/themes/app/menu.html.twig
src/AppBundle/Resources/views/themes/app/page_footer.html.twig
src/AppBundle/Resources/views/themes/app/page_topmenu.html.twig
src/AppBundle/Resources/views/themes/app/pagelayout.html.twig
src/AppBundle/Resources/views/themes/app/pagelayout_variables.html.twig

Implement active state on main menu via JS

NGSTACK-448 Implement active state on main menu via JS 

---

deploy/parameters.php

Tested on titanic, `/var/www/ez/deployment-test`
```
iherak@newtitanic: /var/www/ez/deployment-test $ ll shared/ezpublish_legacy/var/
total 16
drwxr-sr-x 4 deployer www-data 4096 Nov  9 17:42 ./
drwxr-sr-x 3 deployer www-data 4096 Nov  9 17:42 ../
drwxr-sr-x 3 deployer www-data 4096 Nov  9 17:42 site/
drwxr-sr-x 2 deployer www-data 4096 Nov  9 17:42 storage/
```

NGSTACK-471 add 'ezpublish_legacy/var/storage' as a shared directory

---

src/AppBundle/Resources/sass/blocks/list/_grid_featured.scss
src/AppBundle/Resources/views/themes/app/content/overlay/ng_article.html.twig
src/AppBundle/Resources/views/themes/app/content/overlay/ng_blog_post.html.twig
src/AppBundle/Resources/views/themes/app/content/overlay/ng_gallery.html.twig
src/AppBundle/Resources/views/themes/app/content/overlay/ng_news.html.twig
src/AppBundle/Resources/views/themes/app/content/overlay/ng_recipe.html.twig

an issue has occurred from previous changes on overlay templates that specific CSS rules have not been applied to grid_featured block with overlay items in it.
This has been changed, alongside with removal of unnecessary classes on links in overlay templates since this is not necessary anymore (it wasn't necessary even before, but what can you do... :) )

NGSTACK-452 - remove redundant classes and fix grid_featured behaviour

---

src/AppBundle/Resources/config/content_view.yml
src/AppBundle/Resources/views/themes/app/content/full/ng_category.html.twig

Depends on: https://github.com/netgen/ezplatform-site-api/pull/187

NGSTACK-461 Use query type instead of controller for ng category

---

src/AppBundle/Resources/views/themes/common/parts/video.html.twig

This microfix has been done in order to display ng_video overlay templates properly, since the major change of banners did not take videos to account.

Add video poster fix for displaying overlay video template

---

config/app/prepends/content_view.yaml

Two minor improvements:
- removed `visible` condition as it's `true` by default in Site API v4+
- moved `match` block to the end of the view rule

NGSTACK-461: in Site API v4 visible is true by default

---

src/AppBundle/Resources/sass/content/full/_full_page_elements.scss
src/AppBundle/Resources/sass/layout/_breadcrumbs.scss
src/AppBundle/Resources/views/themes/app/content/full/ng_landing_page.html.twig
src/AppBundle/Resources/views/themes/app/search/search.html.twig
src/AppBundle/Resources/views/themes/app/tag/view.html.twig

This PR has:
1. fixes on breadcrumbs styling
2. enable of breadcrumbs on landing pages by default
3. provide styling for pages that cannot have breadcrumbs (search, tags view)
4. content fixes on Layouts to make the default state look nice.
LAYOUT CHANGES:
Landing Page / Fitness,
Landing Page / Healthy Eating:
all changes are on first container block/content inside it
- container: change whitespace top from medium to small
- main title: change from Title (Centered) to Title
- Text below main title: change from align center to align left

NGSTACK-479 - Add fixes for breadcrumbs

---

README.md

Since this repo already has Platform.sh configuration files in it (inherited from Ibexa), here's a button to quick-launch on Platform.sh.  I added it where it seemed to make sense in context, but feel free to move it.  The UTM tags are just so we can keep track of which deploy button is which.
Let me know if you've any questions.

Add Deploy on Paltform.sh button

---

.gitignore
deploy.php
deploy/tasks/app.php
deploy/tasks/assets.php
package.json

With this change, we would not keep production asset builds in the repository any more, but rather have deployer build them locally, and upload them to the server on deploy.
Important parameters:
* `asset_resource_paths` - paths to folders which hold the sources from which the assets are build. These paths are checked for changes before build, and if there are some local uncommitted changes, will not allow deploy to go further.
* `asset_build_base` - web or public, depending on symfony version
* `asset_build_paths` - paths of all the folders within base which should be uploaded
* `asset_exclude_paths` - files or folders which are to be excluded from the upload (typically `assets/app/build_dev`)

NGSTACK-496 remove assets from git and make sure deployer builds them

---

doc/netgen/INSTALL.md

The demo data adds an administrator user to the database, but the password for the account is not documented anywhere.
This pull requests adds the username and password to the install instructions, in the section on importing the database schema and demo data.

Document the password of the administrator user from the demo data

---

deploy.php
deploy/tasks/assets.php

This PR contains two somewhat related fixes:
1. 4df99cceb - seems that in https://github.com/netgen/media-site/pull/61 we forgot to activate the new task to build and deploy assets :) 
2. 266948d - there are cases where we need to redefine composer command, for example `set('bin/composer', 'php7.4 /usr/local/bin/composer2')` in case where there are both multiple versions of php and composer installed on server. This makes sure that `asset_ezplatform_build_command` configured composer instead of hardcoding just `composer` command.

NGSTACK-537 deploy assets fix

---

package.json
webpack.config.default.js

Cause
- old dependencies do not work with Node 16, the latest LTS
Changes
- updated some sass-related dependencies so `yarn install` does not fail
- updated webpack encore package and config file to match the new version API so `yarn build:dev` and `yarn build:prod` would not fail
Testing
- for each Node version from 12, 14, and 16, run:
```bash
yarn install   
yarn build:dev
yarn build:prod
```
all commands should pass

NGSTACK-546 bugfix failing asset install and build

---

config/app/prepends/content_view.yaml

To go with:
- https://github.com/netgen/ibexa-site-api/pull/4
This configures the default no view redirect fallback with `keep_request_method` option se to `%kernel.debug%`.
This will produce `308` redirect in the debug mode, and `301` redirect otherwise (in production).

NGSTACK-379: configure keep_request_method for no view redirect fallback

---

src/AppBundle/Resources/views/themes/common/parts/macros.html.twig

Fix issue where image without link would be without wrapper, which made markup insufficient for styling.

NGSTACK-605 quickfix for image wrapper

---

Makefile

This PR adds command for clearing cache pool (default Redis) in Makefile, into existing `make clear-cache` command. Cache pool is configurable through variable in Makefile.

NGGW-82 Add command for clearing cache pool in Makefile

---

config/app/packages/ez_core_extra.yaml
templates/themes/app/content/full/ng_video.html.twig
templates/themes/app/content/gallery_grid/ng_blog_post.html.twig
templates/themes/app/parts/time.html.twig
templates/themes/common/content/ngcb_preview/ng_blog_post.html.twig
templates/themes/common/content/ngcb_preview/ng_news.html.twig

This uses `lolautruche/ez-core-extra-bundle` to create siteaccess aware Twig global variables used to define date and datetime formats in Twig

NGSTACK-710: Make date formats siteaccess aware

---

app/config/config.yml

Add IDE configuration to open debug links in PHP Storm and VS Code

NGGW-91 add IDE configuration

---

Makefile

As it turns out, each line in the recipe is run in a separate shell :open_mouth: 
`.ONESHELL` directive makes the whole recipe run in a single shell, therefore keeping the node version between the commands.

NGGW-105 fix assets build so it does not use sub-make

---

phpstan-baseline.neon
phpstan.neon

This adds some useful PHPStan ignore rules which are related to how Ibexa handles content fields and their values, e.g.
```php
$content->getFieldValue('title')->text
```
would result in an error:
```
Access to an undefined property Ibexa\Contracts\Core\FieldType\Value::$text
```
I will add more later as I run into them

Add PHPStan baseline to exclude most frequent errors related to Ibexa

---

templates/themes/app/pagelayout/head/title.html.twig

This PR fixes the following issues:
1. It was impossible to set site meta title from the content metadata field. content_meta_data object is being set in another template (meta.html.twig) which is included after the title.html.twig. The logic for the title and other meta tags is now properly separated.
2. When the site_title was taken from the content metadata field, it would be outputted without the dash character + site_name suffix. This is not correct, as the site name is appended to site title if the site title comes from any other source (default generated from path, or site_title being set in the full view template). The content metadata field logic is now moved right before the title tag output, as it is a top-priority override, and it get proper site name suffix

Fix site title override from content metadata field

---

assets/js/components/CookieControl.component.js
assets/js/components/GalleryBlock.component.js
package.json

- fixed "this" eslint error by using static methods
- fixed "unresolved import" by disabling eslint for that line
- not sure why it cannot resolve this import since the way it's defined in the package works and is supported by the webpack version used in the project, obviously
- eslint also supposedly supports this kind of package export with the import plugin, but it's pretty updated and even the most recent update didn't help
- https://webpack.js.org/guides/package-exports/
- added linter:js yarn script, fixed path with globs for eslint and prettier

NGSTACK-779 eslint

---

templates/themes/app/pages/search.html.twig

https://netgen.atlassian.net/browse/NGSTACK-788
I added zero check for maxScore to prevent division by zero error.
This is because maxScore can now be 0 https://github.com/netgen/ibexa-search-extra/pull/3

NGSTACK-788 add max score zero check before division

---

composer.json
templates/themes/app/content/parts/content_fields.html.twig

`ngenhancedlink` in `1.1` added enabling/disabling link labels in the field definition. This updates the field type template and `ngenhancedlink` version.

Bump ngenhancedlink

---

templates/themes/app/pagelayout/cookie_control.html.twig

Social sharing cookies JS component had a syntax error where onRevoke function wasn't closed.

NGSTACK-1 fix broken JS in cookie ribbon

---

templates/themes/app/errors/403.html.twig

This issue was generated by my carelessness. All error pages will now have unified markup.

Fix duplicated wrapper issue on error page

---

assets/js/components/CookieControl.component.js
templates/themes/app/parts/google_tag_manager_code_script.html.twig

Added new logic for google consent. 
- main part is in the google_tag_manager_code_script.html.twig
- enhancing part is in the CookieControl.component.js
- small older bug fixed in the CookieControl.component.js  line 19

NGSTACK-915 - google consent v2

---

composer.json

symfony/serializer-pack v1.3.0 package requires "phpstan/phpdoc-parser": "*":
phpdoc-parser got released with version 2.0 so we need to lock it to 1.33 to avoid exception:
CRITICAL [php] Uncaught Error: Too few arguments to function PHPStan\PhpDocParser\Parser\ConstExprParser::__construct(), 0 passed in /home/iherak/temp/media-site/vendor/symfony/property-info/Extractor/PhpStanExtractor.php on line 76 and exactly 1 expected ["exception" => ArgumentCountError { …}]

NGSTACK-925 Downgrade phpdoc-parser version beacuse of serializer dependency

---

templates/themes/app/pagelayout/cookie_control.html.twig
templates/themes/app/pagelayout/footer.html.twig

There are situations where we have third party cookie policy and with that it's own cookie settings. In that case we do not want to show our cookie settings button.

Do not show cookie settings button if there is no related cookie policy

---

src/Kernel.php

Symfony has a problem with overriding error reporting levels that can not be fixed by configuration in yaml.
There are 2 issuses opened, but nothing has been done regarding this:
https://github.com/symfony/symfony-docs/issues/17592
https://github.com/symfony/symfony/issues/35575

Exclude unwanted logs in error reporting

---

assets/js/components-noncritical.js
assets/js/components/PageHeader.component.js

- changed main selector to .site-header instead of html, so it only tries to initialise the component when site-header is present instead of always. I am not sure why "html" was used before, but this should work as well from what I've noticed (everything used in the component seems to be inside the header anyway, though it is not used for DOM queries)
- added nullish query selector to headerSearch because that component can be null, fallback to null instead of default undefined
- added nullish call to focus on input because idk if it can not exist in case the toggle exists, might be unnecessary
The rest seems fine as it already has null checks in init functions for important elements.
Testing should be done with whole or partial removal of header parts according to real use cases for …

NGSTACK-978 add more null checks, change selector that inits component
