netgen/media-site

src/AppBundle/Resources/views/themes/common/parts/macros.html.twig
Set default url to false instead hash sign
Place a tags under if statement to prevent automatic rendering
Otherwise content would be rendered as link even if url is not defined
=> Place a tags under if statement

src/AppBundle/Resources/views/themes/common/parts/cookie_control.html.twig
Added changes for cookie control template with new ng_cookie_control object and logic.
=> NGSTACK-236 Added changes on cookie_control template

app/config/services.yml, src/AppBundle/AppBundle.php, src/AppBundle/DependencyInjection/CompilerPass/DisableVerticalWhitespacePass.php, src/AppBundle/Resources/config/services.yml
Related to https://github.com/netgen/site-bundle/pull/11
// TODO
- implement template and CSS support in media site
- adapt demo data
=> Enabling verctical whitespace v2 plugin, disabling v1

app/config/prod/config.yml, app/config/sentry.yml, composer.json, deploy.php, deploy/files/.env.dist, deploy/files/parameters.stage.yml, deploy/hosts.php, deploy/parameters.php, deploy/tasks/database.php, deploy/tasks/deploy_log.php, deploy/tasks/logs.php, deploy/tasks/overrides.php, deploy/tasks/rsync.php, deploy/tasks/sentry.php, deploy/tasks/server.php, deploy/tasks/slack.php
Files that need to be changed per project are:
* `deploy/hosts.php`
* `deploy/parameters.php`
For server specific configuration, edit the `deploy/hosts.php` file and add proper hostname, adjust users etc.
For project specific configuration, edit the `deploy/parameters.php` file with project specifics (app name, repository, branch, sentry configuration etc)
=> NGSTACK-315 add basic deployer configuration

config/app/packages/ezplatform.yaml, config/app/prepends/content_view.yaml
Updated view configuration for changes in Site API from https://github.com/netgen/ezplatform-site-api/pull/169
=> Update view config for reorganization in Site API

doc/netgen/SEARCH_SUGGESTIONS.md, src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/views/themes/app/search/search.html.twig
This PR provides implementation for the [spellcheck suggestions search feature](https://docs.netgen.io/projects/search-extra/en/latest/reference/spellcheck_suggestions.html) from Netgen eZ Search Extra bundle.
**Note:** this PR depends on this PR: https://github.com/netgen/site-bundle/pull/14 from Netgen Site Bundle!
**Note 2:** in order for the feature to work, some adjustments on the Solr configuration are needed, which is documented in the provided MD file.
=> NGSTACK-325 Search spellcheck suggestion

src/AppBundle/Resources/views/themes/app/search/search.html.twig
normalize search result item score based on adapter maxScore value
=> NGSTACK-468 normalize search result item score

README.md, app/AppKernel.php, app/config/config.yml, app/config/routing.yml, composer.json, doc/netgen/TRANSLATIONS.md
Required changes:
Create database tables:
`php bin/console doctrine:schema:update --force`
Import existing translations into database:
`php bin/console lexik:translations:import AppBundle`
Install assets:
`php bin/console assets:install --symlink`
Clear caches:
`php bin/console cache:clear`
=> NGSTACK-464 Prime translations bundle

src/AppBundle/Resources/sass/_typography.scss, src/AppBundle/Resources/sass/_variables.scss, src/AppBundle/Resources/sass/bootstrap_import/_bootstrap_variables.scss, src/AppBundle/Resources/sass/layout/_breadcrumbs.scss, src/AppBundle/Resources/sass/layout/_layout.scss, src/AppBundle/Resources/views/themes/app/content/full/ng_article.html.twig, src/AppBundle/Resources/views/themes/app/content/full/ng_blog_post.html.twig, src/AppBundle/Resources/views/themes/app/content/full/ng_feedback_form.html.twig, src/AppBundle/Resources/views/themes/app/content/full/ng_news.html.twig, src/AppBundle/Resources/views/themes/app/content/full/ng_recipe.html.twig, src/AppBundle/Resources/views/themes/app/content/full/ng_topic.html.twig, src/AppBundle/Resources/views/themes/app/page_path.html.twig
- Add new color variable
- Update breadcrumbs template and styles
- Enable breadcrumbs on all full views other than ng_landing_page and ng_frontpage FV
=> NGSTACK-451 Update full view breadcrumbs

src/AppBundle/Resources/views/themes/common/parts/macros.html.twig
Just a small change by @emodric 's request.
=> NGSTACK-452 rename macro to related_content_link

composer.json, src/AppBundle/Resources/config/content_view.yml
This updated query type configuration for expression improvements released in Site API 3.7.
=> Update query type configuration for Site API 3.7

src/AppBundle/Resources/es6/ngsite.js, src/AppBundle/Resources/sass/_cookie_control.scss, src/AppBundle/Resources/translations/messages.en.yml, src/AppBundle/Resources/views/themes/app/page_footer.html.twig, src/AppBundle/Resources/views/themes/common/parts/cookie_control.html.twig
For this upgrade to finish,  upgrade on https://github.com/netgen/javascript-cookie-control will also be needed.
=> NGSTACK-503 cookie policy upgrade

captainhook.template.json
change default php configuration to be compatible with all systems
=> NGSTACK-527 unify php path

captainhook.template.json
For example MDX8-123, MX8D-234
=> NGSTACK-540 allow numbers in the middle of task id

captainhook.template.json
Related PR: https://github.com/netgen/git-hooks/pull/8
=> NGSTACK-546 js linters hook

config/app/prepends/content_view.yaml
To go with:
- https://github.com/netgen/site-bundle/pull/23
- https://github.com/netgen/ibexa-site-api/pull/3
This configures fallback full view redirect to the homepage.
=> NGSTACK-379: configure homepage redirect for content without the configured full view

config/app/prepends/content_view.yaml
To be merged after https://github.com/netgen/ibexa-site-api/pull/5
=> NGSTACK-379: update redirect config

captainhook.template.json, composer.json, phpstan.neon
Related PR: https://github.com/netgen/git-hooks/pull/9
=> NGGW-44 activate phpstan hook and add basic phpstan configuration

src/AppBundle/Resources/es6/app.js, src/AppBundle/Resources/es6/components/CookieControl.component.js, src/AppBundle/Resources/es6/components/LazyLoading.component.js, src/AppBundle/Resources/es6/ngsite.js
@markosandalj
Merging all JS changes into one consolidated branch
=> Nggw 55 js structure updates

doc/apache2/netgen-site-vhost.conf, doc/nginx/ez_params.d/ez_legacy_rewrite_params, src/AppBundle/Resources/symlink/root_dev/.htaccess, src/AppBundle/Resources/symlink/root_prod/.htaccess
Changes
--------
- added rewrite rules for sitemaps based on previous and with help from IH
Testing
--------
- *I* don't know
=> NGGW-99 sitemap rewrite rules

templates/themes/app/parts/content_fields.html.twig
https://netgen.atlassian.net/browse/NGSTACK-712
=> NGSTACK-712 use ng_view_content_embedded rendering to improve performance

config/app/prepends/ibexa/content_view.yaml, templates/themes/app/content/link.html.twig, templates/themes/app/parts/content_fields.html.twig
To be merged with https://github.com/netgen/ibexa-fieldtype-enhanced-link/pull/25
=> NGSTACK-714: generate plain link directly

composer.json, config/bundles.php
https://netgen.atlassian.net/browse/NGSTACK-658
I added link from content to its content type and link from content type to search with that content type as filter.
=> Ngstack 658 ibexa4 admin enhancements

config/app/prepends/ibexa/content_view.yaml
To be merged with https://github.com/netgen/ibexa-site-api/pull/16
=> NGSTACK-714: update for renamed config

.gitignore, .vscode/extensions.json, .vscode/settings.json
As discussed with @iherak I added basic editor settings for vs code where we defined tabSize and file end of line for frequently used file types. I also added file for recommended vs code extensions that can later be updated if needed.
=> Nggw 106 vscode settings

templates/themes/app/page_head_style.html.twig
Introduced in https://github.com/netgen/media-site/commit/087936ab71a51cf8eb24f5c0380545cc2b319889
=> Fix duplicate rel attribute

templates/themes/app/content/parts/related_items.html.twig, templates/themes/app/content/views/full/ng_category.html.twig
There is no need for a dedicated controller and template any more.
=> Rewrite related items inside the template

package.json
See https://github.com/js-cookie/js-cookie
=> NGSTACK-764: add js-cookie dependency

assets/sass/content/_ezrichtext.scss
Added !important to override Ibexa's inline css
=> NGSTACK-770 add 'important' to override ibexa's inline css

composer.json, templates/themes/app/content/parts/content_fields.html.twig
Update for fix from https://github.com/netgen/ibexa-fieldtype-enhanced-link/pull/28
=> NGSTACK-818: test for link availability

config/app/packages/ez_core_extra.yaml
To display a proper year in dates, year format needs to be modified.
=> NGSTACK-1 update date formats with correct year format

config/app/packages/opengraph.yaml, templates/themes/app/pagelayout/head/link.html.twig
task id: https://netgen.atlassian.net/browse/NGSTACK-807
Related to: https://github.com/netgen/NetgenOpenGraphBundle/pull/13
=> NGSTACK-807 add canonical tag to main location

Makefile
Add ibexa-assets to MakeFile because assets were not building as they should.
=> NGSTACK-817 Add ibexa-assets to MakeFile

templates/themes/app/content/parts/content_fields.html.twig, templates/themes/app/content/views/embed/image.html.twig
I added internal and external link option for embeded images in rich text.
=> IOTA-649 add internal and external link option for embeded images

composer.json, templates/themes/app/pagelayout.html.twig
https://github.com/netgen/ibexa-site-api/pull/11 will introduce a BC change, changing `Location::$path` to `Location::$pathArray`. This updates accordingly.
To be merged after Site API v6 is released.
=> NGSTACK-673: update for breaking change in Site API

assets/js/components/CookieControl.component.js
Added fix for cookie consent event trigger on Save and Close button.
=> NGSTACK-780 - cookie consent on save listener fix

assets/sass/layout/_breadcrumbs.scss, templates/themes/app/pagelayout/breadcrumbs.html.twig
- added nav element as suggested by wcag
- fixed breadcrumbs typo 
- added aria-current to last item in breadcrumbs as suggested by wcag
=> NGSTACK-947 - breadcrumbs nav changes
